name = "Axial"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6352bee8b559662f2d2a0c09f15cec2f799b32e5f793c6a5c90d2662bec4dda2"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
